name       : xorg-driver-input-libinput
version    : 0.15.0
release    : 2
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-input-libinput-0.15.0.tar.gz : 69eeac87bfb66587be9c8af1473300cb5d89981e08365736d8920cfd4060ed19
license    : MIT
summary    : X11 libinput based input driver
description: |
    X11 libinput based input driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(libinput)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fedora-use-unaccelerated-vmask-on-input-ABI-21.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
