name       : xorg-driver-input-libinput
version    : 0.22.0
release    : 5
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-libinput-0.22.0.tar.gz : 5ecd03dd71207047d2390ed2d7a3738795897e138efecd56d10d050c824940f1
license    : MIT
summary    : X11 libinput based input driver
component  : xorg.driver
description: |
    X11 libinput based input driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(libinput)
    - pkgconfig(xorg-server)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fedora-use-unaccelerated-vmask-on-input-ABI-21.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
