name       : xorg-driver-input-libinput
version    : 1.2.0
release    : 28
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-libinput-1.2.0.tar.gz : a4bf36d40daede0ea8678e5da5a5205e3bddc3d375d4c1991336ddaf96929bf6
license    : MIT
summary    : X11 libinput based input driver
component  : xorg.driver
description: |
    X11 libinput based input driver
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(libinput)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/X11/xorg.conf.d/40-libinput.conf $installdir/usr/share/X11/xorg.conf.d/60-libinput.conf
check      : |
    %make check
