name       : xorg-driver-input-libinput
version    : 0.19.0
release    : 4
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-libinput-0.19.0.tar.gz : 9468ea38f8699d73a9630bf216aa4bcf7eacbd93e8178c130eabc0751dff9152
license    : MIT
summary    : X11 libinput based input driver
component  : xorg.driver
description: |
    X11 libinput based input driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(libinput)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fedora-use-unaccelerated-vmask-on-input-ABI-21.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
