name       : xorg-driver-input-libinput
version    : 0.26.0
release    : 15
source     :
    - https://www.x.org/releases/individual/driver/xf86-input-libinput-0.26.0.tar.gz : 2052e6bc5f640fb65f6db67a20682953886e9ed234a4b390a71d5794a268996c
license    : MIT
summary    : X11 libinput based input driver
component  : xorg.driver
description: |
    X11 libinput based input driver
optimize   : no-bind-now
builddeps  :
    - pkgconfig(libinput)
    - pkgconfig(xorg-server)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fedora-use-unaccelerated-vmask-on-input-ABI-21.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/X11/xorg.conf.d/40-libinput.conf $installdir/usr/share/X11/xorg.conf.d/60-libinput.conf
